
<table border='1' cellspacing='1' width='100%'><tr><td>Date</td><td>Time</td><td>Source</td><td>Event</td><td>Message</td><td>StackTrace</td><td>Condition</td></tr><tr><td valign="top">8/11/2018&#160;</td><td valign="top">8:03:55 PM&#160;</td><td valign="top"><a name="1" href="#1">1.ManageUserModel</a>&#160;</td><td valign="top">save&#160;</td><td valign="top">An error occurred while updating the entries. See the inner exception for details.&#160;</td><td valign="top">   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at Demo.Service.StudentService.Save(Student objStudent) in D:\DevArea\Projects\DemoApplication\Demo.Service\Student\Student.cs:line 45
   at Demo.Model.StudentModel.Save() in D:\DevArea\Projects\DemoApplication\Demo.Model\Student\StudentModel.cs:line 120&#160;</td><td valign="top">&#160;</td></tr>
